---
title: "Teste"
author: "Germano Andrade"
date: "03/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Capítulo 1

## Questão 3
Construa a distribuição de freqências para as variaveis:

População Urbana

```{r}
dadosPop <- cd_brasil$pop_urbana
dadosPop <- dadosPop[!is.na(dadosPop)]
#table(cut(dadosPop, b=c(-Inf,700000, 2000000,4000000,6000000,8000000,Inf), dig.lab = 8))
Frequencia_ni <- table(cut(dadosPop, b=c(-Inf,700000, 2000000,4000000,6000000,8000000,Inf), dig.lab = 8))
Frequencia_fi <- Frequencia_ni/sum(Frequencia_ni)
Porcentagem_100fi <- Frequencia_fi*100
Tabela_Pop <- matrix(c(Frequencia_ni, Frequencia_fi, Porcentagem_100fi), nrow = 6, ncol=3)
Tabela_Pop <- rbind(Tabela_Pop, sum(Tabela_Pop[,1]))
colnames(Tabela_Pop) <- c("Frequência ni","Frequência fi","Porcentagem 100fi")
row.names(Tabela_Pop) <- c("Menor que 700.000", "Entre 700.000 e 2.000.000", "Entre 2.000.000 e 4.000.000", "Entre 2.000.000 e 4.000.000", "Entre 6.000.000  e 8.000.000", "Maior que 8.000.000", "Total")
Tabela_Pop

```

